#Build stage
FROM arm32v7/maven AS build-env

ADD . /rfc3161timestampingserver

WORKDIR rfc3161timestampingserver

RUN mvn -U compile package assembly:single

# Run it
FROM bellsoft/liberica-openjdk-alpine

COPY --from=build-env /rfc3161timestampingserver/target/*-jar-with-dependencies.jar /app/rfc3161timestampingserver.jar

EXPOSE 7000

CMD ["java", "-jar", "/app/rfc3161timestampingserver.jar"]