name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn  -fn -Dmaven.test.failure.ignore=true --batch-mode -U clean compile test surefire-report:report-only site install package assembly:single
      - run: mkdir staging && cp target/*with-dependencies.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      - name: Generate JaCoCo Badge
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          badges-directory: target/site/jacoco/badges
      - name: Publish coverage report to GitHub Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/site/
